- include_tasks: "check_release.yml"

- name: Remove junk
  alcatel.aos8.aos8_command:
    commands:
      - "rm -rf uboot*"
      - "rm -rf fpga*"
  when: release == '8'
  
- name: Remove junk
  alcatel.aos8.aos8_command:
    commands:
     - "rm KFfpga.upgrade_kit"
  when: release == '6'