- include_tasks: "check_release.yml"

- name: Collect raw hardware-info output
  alcatel.aos8.aos8_command:
    commands:
      - "show hardware-info"
  register: raw_hardware_info_output
- name: Build TextFSM template path
  set_fact:
    template_path: "{{ textfsm_folder }}/ale_aos{{ release }}_show_hardware-info.textfsm"

- name: Parse fpga version
  set_fact:
    fpga_version: "{{ (raw_hardware_info_output.stdout[0] | ansible.netcommon.parse_cli_textfsm(template_path)).0 }}"
- name: Format fpga version
  set_fact:
    fpga_version: "{{ fpga_version['fpga_version'] }}"
    
- name: Display fpga version
  debug:
    msg: "{{ fpga_version }}"