- include_tasks: "tasks/is_switch_virtual_chassis.yml"
- include_tasks: "tasks/check_running_directory_status.yml"

- name: Check virtual chassis status (only if switch is virtual chassis)
  include_tasks: "tasks/check_virtual_chassis_status.yml"
  when: is_virtual_chassis | default(false)

- name: Set virtual chassis safe status for non-virtual chassis switches
  set_fact:
    is_virtual_chassis_safe: true
  when: not (is_virtual_chassis | default(false))

- name: Debug - Show final check results
  debug:
    msg: |
      Final Safety Check Results:
      - is_virtual_chassis: {{ is_virtual_chassis | default('NOT_SET') }}
      - is_running_directory_safe: {{ is_running_directory_safe | default('NOT_SET') }}
      - is_virtual_chassis_safe: {{ is_virtual_chassis_safe | default('NOT_SET') }}
      - Combined result: {{ (is_running_directory_safe | default(false)) and (is_virtual_chassis_safe | default(false)) }}

- name: Set overall switch safety status for update
  set_fact:
    is_switch_safe_to_update: "{{ is_running_directory_safe and is_virtual_chassis_safe }}"