---
# tasks file for alcatel-omniswitch-software-update
- name: Verify if switch is safe to update
  include_tasks: "is_switch_safe_to_update.yml"

- name: ❌ Safety Check Failed - Update Aborted
  fail:
    msg: |
      ❌ SWITCH SAFETY CHECK FAILED!
      
      The switch is not in a safe state for software updates.
      {% if not (is_running_directory_safe | default(true)) %}
      • Running Directory Check: FAILED
      {% endif %}
      {% if not (is_virtual_chassis_safe | default(true)) %}
      • Virtual Chassis Check: FAILED
      {% endif %}
      
      Please resolve these issues before attempting the update.
  when: not is_switch_safe_to_update

- name: Saving current chassis state
  include_tasks: "save_chassis_state.yml"



- name: Uploading FPGA files
  upload_file: 
    host: "{{ inventory_hostname }}"
    port: 22
    username: "{{ omniswitch_username }}"
    password: "{{ omniswitch_password }}"
    remote_path: "/flash"
    files: "{{ fpga_files }}"
  when: fpga_files is defined and fpga_files | length > 0

- name: Uploading U-Boot files
  upload_file: 
    host: "{{ inventory_hostname }}"
    port: 22
    username: "{{ omniswitch_username }}"
    password: "{{ omniswitch_password }}"
    remote_path: "/flash"
    files: "{{ uboot_files }}"
  when: uboot_files is defined and uboot_files | length > 0

- name: Uploading Firmware files
  upload_file: 
    host: "{{ inventory_hostname }}"
    port: 22
    username: "{{ omniswitch_username }}"
    password: "{{ omniswitch_password }}"
    remote_path: "/flash/working"
    files: "{{ firmware_files }}"
  when: firmware_files is defined and firmware_files | length > 0

- name: Applying update
  block:
    - include_tasks: "tasks/update_uboot.yml"
    - include_tasks: "tasks/update_fpga.yml"
    
    
    - name: Execute reload from working with rollback-timeout {{ rollback_timeout }}
      reload_switch:
        host: "{{ inventory_hostname }}"
        username: "{{ omniswitch_username }}"
        password: "{{ omniswitch_password }}"
        rollback_timeout: "{{ rollback_timeout }}"
        directory: "working"
        release: "{{ release }}"
      register: reload_output
      ignore_unreachable: true
      ignore_errors: true
      async: 60
      poll: 0

- name: Wait for switch to Become Unreachable
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: absent
    timeout: "{{ wait_for_timeout }}"

- name: Wait for switch to Become reachable
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: present
    timeout: "{{ wait_for_timeout }}"

- name: Reset SSH connection
  meta: reset_connection

- name: Verify chassis state
  include_tasks: "compare_chassis_state.yml"

- name: Finalize update
  block:    
    - name: Cancel planned reload
      reload_cancel:
        host: "{{ inventory_hostname }}"
        username: "{{ omniswitch_username }}"
        password: "{{ omniswitch_password }}"
      register: cancel_result

    - include_tasks: delete_update_junk.yml

    - name: Write memory flash synchro
      include_tasks: "write_memory.yml"

    
  when:
    - not is_chassis_different
    


