- include_tasks: "tasks/check_release.yml"

- name: Updating FPGA (CMM)
  alcatel.aos8.aos8_command:
    commands:
      - "update fpga-cpld cmm all file {{ fpga_file_name }}"
  when: release == '8'
  
- name: Updating FPGA (NI)
  alcatel.aos8.aos8_command:
    commands:
      - "update fpga ni all"
  when: release == '6'