- include_tasks: "check_release.yml"

- name: Write memory flash-synchro
  alcatel.aos8.aos8_command:
    commands:
      - "write memory flash-synchro"
  when: release == '8'

- name: Write memory flash-synchro
  alcatel.aos8.aos8_command:
    commands:
      - "write memory flash-synchro"
  when: release == '6'